In [25]:
import numpy as np 

In [10]:
mat=np.array([[1,0,-1],[4,0,0],[0,2,-2]])
b=np.array([0,2,1])
x=np.linalg.solve(mat,b)
x

array([0.5, 1. , 0.5])

In [12]:
x*2

array([1., 2., 1.])

In [16]:
mat=np.array([[1,0,-2],[1,4,-4],[1,2,0],[0,1,-1]])
print(mat)
b=np.array([0,1,2,0])
m=np.linalg.lstsq(mat,b,rcond=None)
print(m[0]*2)

[[ 1  0 -2]
 [ 1  4 -4]
 [ 1  2  0]
 [ 0  1 -1]]
[2. 1. 1.]


In [27]:
mat=np.array([[1,0,0,-2,0,0],[1,0,0,0,0,-1],[4,4,4,-4,-12,-4],[0,1,0,0,-2,0],[0,1,1,-1,-3,-1],[0,0,2,0,0,0]])
print(mat)
b=np.array([0,0,1,0,0,2])
m=np.linalg.lstsq(mat,b,rcond=None)
print(m[0]*4*2)

[[  1   0   0  -2   0   0]
 [  1   0   0   0   0  -1]
 [  4   4   4  -4 -12  -4]
 [  0   1   0   0  -2   0]
 [  0   1   1  -1  -3  -1]
 [  0   0   2   0   0   0]]
[ 2. 10.  8.  1.  5.  2.]


In [28]:
b

array([0, 0, 1, 0, 0, 2])

In [30]:
sum(mat[2]*m[0]*4*2)/b[2]

7.999999999999982